Repository AY2223S2-CS2113T-T09-3/tp, pull requests merged in 2023-03, with the labels that each got.

#22 Implemented adding of ingredients of a specified quantity
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/DukeException.java
  src/main/java/seedu/duke/DukeSession.java
  src/main/java/seedu/duke/Ingredient.java
  src/main/java/seedu/duke/IngredientList.java
  src/main/java/seedu/duke/command/factory/misc/AddCommandFactory.java
  src/main/java/seedu/duke/command/misc/AddCommand.java
  src/test/java/seedu/duke/command/misc/AddCommandTest.java
Labels: priority.High

#27 Implement listing of possible recipes
  src/main/java/seedu/duke/DukeSession.java
  src/main/java/seedu/duke/IngredientList.java
  src/main/java/seedu/duke/command/factory/misc/RecipePossibleCommandFactory.java
  src/main/java/seedu/duke/command/misc/AddCommand.java
  src/main/java/seedu/duke/command/misc/RecipePossibleCommand.java
  src/main/java/seedu/duke/ingredient/Ingredient.java
  src/main/java/seedu/duke/ingredient/IngredientList.java
  src/main/java/seedu/duke/recipe/Instruction.java
  src/main/java/seedu/duke/recipe/InstructionList.java
  src/main/java/seedu/duke/recipe/Recipe.java
  src/main/java/seedu/duke/recipe/RecipeList.java
  src/test/java/seedu/duke/command/misc/AddCommandTest.java
Labels: priority.High

#28 Implemented Removing ingredient of specified quantity and JUnit
  src/main/java/seedu/duke/DukeSession.java
  src/main/java/seedu/duke/command/factory/misc/RemoveCommandFactory.java
  src/main/java/seedu/duke/command/misc/AddCommand.java
  src/main/java/seedu/duke/command/misc/RecipePossibleCommand.java
  src/main/java/seedu/duke/command/misc/RemoveCommand.java
  src/main/java/seedu/duke/ingredient/Ingredient.java
  src/test/java/seedu/duke/command/misc/AddCommandTest.java
  src/test/java/seedu/duke/command/misc/RemoveCommandTest.java
Labels: priority.High

#31 Implement Ingredients Storage
  build.gradle
  src/main/java/seedu/duke/DukeSession.java
  src/main/java/seedu/duke/command/misc/AddCommand.java
  src/main/java/seedu/duke/storage/IngredientStorage.java
Labels: priority.High

#33 Implement RecipePossibleCommand testing
  .gitignore
  src/main/java/seedu/duke/DukeSession.java
  src/main/java/seedu/duke/command/misc/AddCommand.java
  src/main/java/seedu/duke/command/misc/HelloWorldCommand.java
  src/main/java/seedu/duke/command/misc/RecipePossibleCommand.java
  src/main/java/seedu/duke/command/misc/RemoveCommand.java
  src/main/java/seedu/duke/recipe/RecipeList.java
  src/main/java/seedu/duke/router/CommandRouterNode.java
  src/test/java/seedu/duke/command/misc/AddCommandTest.java
  src/test/java/seedu/duke/command/misc/RecipePossibleCommandTest.java
  src/test/java/seedu/duke/command/misc/RemoveCommandTest.java
  src/test/java/seedu/duke/parser/CommandArgumentsTest.java
Labels: type.Task

#46 Add more default recipes and ingredients to the lists
  src/main/resources/ingredients.json
  src/main/resources/recipes.json
Labels: type.Story, priority.High

#54 Add calorie counts to recipes and add commands to print calorie counts of recipes
  src/main/java/seedu/mealcompanion/command/misc/RecipeDetailCommand.java
  src/main/java/seedu/mealcompanion/recipe/Recipe.java
  src/main/java/seedu/mealcompanion/serde/SerializableRecipe.java
  src/main/resources/recipes.json
  src/test/java/seedu/mealcompanion/command/misc/RecipeAllCommandTest.java
  src/test/java/seedu/mealcompanion/command/misc/RecipePossibleCommandTest.java
Labels: type.Story, priority.Medium

#62 Implemented removing the ingredients needed to make a specified recipe from inventory
  src/main/java/seedu/mealcompanion/MealCompanionSession.java
  src/main/java/seedu/mealcompanion/command/factory/misc/MakeCommandFactory.java
  src/main/java/seedu/mealcompanion/command/misc/AddCommand.java
  src/main/java/seedu/mealcompanion/command/misc/MakeCommand.java
  src/main/java/seedu/mealcompanion/command/misc/RemoveCommand.java
  src/test/java/seedu/mealcompanion/command/misc/MakeCommandTest.java
Labels: type.Story, priority.Medium

#65 Implement showing cook and prep time for recipes
  src/main/java/seedu/mealcompanion/command/misc/RecipeDetailCommand.java
  src/main/java/seedu/mealcompanion/recipe/Recipe.java
  src/main/java/seedu/mealcompanion/serde/SerializableRecipe.java
  src/main/resources/recipes.json
  src/test/java/seedu/mealcompanion/command/misc/RecipeAllCommandTest.java
  src/test/java/seedu/mealcompanion/command/misc/RecipePossibleCommandTest.java
Labels: type.Story, priority.Medium

#68 Add recipe related commands and recipe class to developer guide
  docs/DeveloperGuide.md
  docs/UML diagrams/RecipeAllCommandSequence.puml
  docs/UML diagrams/RecipeDetailCommandSequence.puml
  docs/UML diagrams/RecipePossibleCommandSequence.puml
  docs/UML diagrams/Recipes.puml
  docs/images/RecipeAllCommandSequence.png
  docs/images/RecipeDetailCommandSequence.png
  docs/images/RecipePossibleCommandSequence.png
  docs/images/RecipeUML.png
Labels: type.Task

#74 Implemented clear command
  src/main/java/seedu/mealcompanion/MealCompanionSession.java
  src/main/java/seedu/mealcompanion/command/factory/misc/ClearCommandFactory.java
  src/main/java/seedu/mealcompanion/command/misc/AddCommand.java
  src/main/java/seedu/mealcompanion/command/misc/ClearCommand.java
  src/main/java/seedu/mealcompanion/command/misc/MakeCommand.java
  src/main/java/seedu/mealcompanion/command/misc/RemoveCommand.java
  src/main/java/seedu/mealcompanion/ingredient/IngredientList.java
  src/test/java/seedu/mealcompanion/command/misc/ClearCommandTest.java
Labels: type.Story, priority.Low

#82 Week 11 taskings + refactor code
  src/main/java/seedu/mealcompanion/MealCompanionSession.java
  src/main/java/seedu/mealcompanion/command/factory/misc/AddCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/misc/ClearCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/misc/MakeCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/misc/RecipeAllCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/misc/RecipeAlmostCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/misc/RecipeDetailCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/misc/RecipeNeedCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/misc/RecipePossibleCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/misc/RecipeRandomCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/misc/RemoveCommandFactory.java
  src/main/java/seedu/mealcompanion/command/ingredients/AddCommand.java
  src/main/java/seedu/mealcompanion/command/ingredients/ClearCommand.java
  src/main/java/seedu/mealcompanion/command/ingredients/IngredientsListCommand.java
  src/main/java/seedu/mealcompanion/command/ingredients/RemoveCommand.java
  src/main/java/seedu/mealcompanion/command/misc/RecipeDetailCommand.java
  src/main/java/seedu/mealcompanion/command/misc/RecipeRandomCommand.java
  src/main/java/seedu/mealcompanion/command/recipe/MakeCommand.java
  src/main/java/seedu/mealcompanion/command/recipe/RecipeAllCommand.java
  src/main/java/seedu/mealcompanion/command/recipe/RecipeAlmostCommand.java
  src/main/java/seedu/mealcompanion/command/recipe/RecipeCommand.java
  src/main/java/seedu/mealcompanion/command/recipe/RecipeDetailCommand.java
  src/main/java/seedu/mealcompanion/command/recipe/RecipeNeedCommand.java
  src/main/java/seedu/mealcompanion/command/recipe/RecipePossibleCommand.java
  src/main/java/seedu/mealcompanion/command/recipe/RecipeRandomCommand.java
  src/main/java/seedu/mealcompanion/ingredient/IngredientList.java
  src/main/java/seedu/mealcompanion/recipe/Instruction.java
  src/main/java/seedu/mealcompanion/recipe/InstructionList.java
  src/main/java/seedu/mealcompanion/recipe/Recipe.java
  src/main/java/seedu/mealcompanion/recipe/RecipeList.java
  src/test/java/seedu/mealcompanion/command/misc/AddCommandTest.java
  src/test/java/seedu/mealcompanion/command/misc/ClearCommandTest.java
  src/test/java/seedu/mealcompanion/command/misc/MakeCommandTest.java
  src/test/java/seedu/mealcompanion/command/misc/RecipeAllCommandTest.java
  src/test/java/seedu/mealcompanion/command/misc/RecipeNeedCommandTest.java
  src/test/java/seedu/mealcompanion/command/misc/RecipePossibleCommandTest.java
  src/test/java/seedu/mealcompanion/command/misc/RemoveCommandTest.java
  src/test/java/seedu/mealcompanion/recipe/RecipeListTest.java
Labels: type.Task

#85 Implement allergens command
  src/main/java/seedu/mealcompanion/MealCompanionSession.java
  src/main/java/seedu/mealcompanion/command/allergen/AllergenAddCommand.java
  src/main/java/seedu/mealcompanion/command/allergen/AllergenListCommand.java
  src/main/java/seedu/mealcompanion/command/allergen/AllergenRemoveCommand.java
  src/main/java/seedu/mealcompanion/command/factory/allergen/AllergenAddCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/allergen/AllergenListCommandFactory.java
  src/main/java/seedu/mealcompanion/command/factory/allergen/AllergenRemoveCommandFactory.java
  src/main/java/seedu/mealcompanion/command/recipe/MakeCommand.java
  src/main/java/seedu/mealcompanion/command/recipe/RecipeCommand.java
  src/main/java/seedu/mealcompanion/command/recipe/RecipePossibleCommand.java
  src/main/java/seedu/mealcompanion/recipe/IngredientDatabase.java
  src/main/java/seedu/mealcompanion/recipe/IngredientMetadata.java
  src/main/java/seedu/mealcompanion/ui/MealCompanionUI.java
  src/test/java/seedu/mealcompanion/command/misc/RecipePossibleCommandTest.java
Labels: priority.High
